### PR TITLE
fix: remove cluster entity

### LINKED ISSUE #87: Remove EOL cluster entity definition.
Remove the Cluster entity dashboard from the Explorer. An [EOL](https://discuss.newrelic.com/t/q1-bulk-eol-announcement-fy23/181744) but the cluster entity has not been removed.

### PR DESCRIPTION
**Pull request by gsanchezgavier**
fixes #87 

# Breaking

- Removing the Cluster entity generation. This entity didn't contain any metrics related. And it's deprecation was announced on this [EOL](https://discuss.newrelic.com/t/q1-bulk-eol-announcement-fy23/181744)

### CODE REVIEW

**Comment by gsanchezgavier** [comment]
rebased from master after merging #88

File: src/metrics/metric_test.go [hunk 1]
```diff
@@ -15,6 +17,17 @@ import (
 	"github.com/stretchr/testify/assert"
 )
 
+func TestMain(m *testing.M) {
+	// TODO remove global args.
+	// This test are heavily based on global args to create entities.
+	args.GlobalArgs = args.RabbitMQArguments{
```
Comment (paologallinaharbur) [inline src/metrics/metric_test.go:23]: I am not getting what we are testing here 🤔

**Review by paologallinaharbur — APPROVED** [review]
just a doubt regarding a test!

File: src/metrics/metric_test.go (hunk 1 above)
Comment (gsanchezgavier) [reply src/metrics/metric_test.go:23]: that was added to the cluster_test.go to test that the entity names contains the host and the port , but also affects other tests where that is being checked since it affects all entities. 

Since I'm removing the `cluster_test.go` file and the TestMain applies to all package tests I needed to add it again.

Comment (paologallinaharbur) [reply src/metrics/metric_test.go:23]: ah ok I did not notice it was a test main 😶‍🌫️
