### PR TITLE
Fix clusterName and entity collisions

### LINKED ISSUE #73: name collisions when used in many k8 clusters
## Description
in "Explorer" page all rabbitmq instances from different k8 clusters have the same name "ra-cluster:rabbit@rabbitmq-0.rabbitmq.default.svc.cluster.local:clustername=rabbit@rabbitmq-0.rabbitmq.default.svc.cluster.local" and grouped as single server

## Expected Behavior
something like done for redis (include name of cluster into name)

## Steps to Reproduce
```
          "newrelic-infrastructure":
              "integrations_config":
              - "data":
                  "discovery":
                    "command":
                      "exec": "/var/db/newrelic-infra/nri-discovery-kubernetes"
                      "match":
                        "label.app": "rabbitmq"
                  "integrations":
                  - "env":
                      "HOSTNAME": "${discovery.ip}"
                      "PASSWORD": "**"
                      "PORT": 15672
                      "USERNAME": "**"
                    "labels":
                      "domain": "*.com"
                      "env": "staging"
                      "project_label": "*"
                    "name": "nri-rabbitmq"
                "name": "rabbitmq-config.yml"

```
## Additional context
I have tried NODE_NAME_OVERRIDE but it didn't help

### PR DESCRIPTION
**Pull request by gsanchezgavier**
# Breaking
Replace the attribute `clusterName` to `rabbitmqClusterName` to avoid collisions with the `clusterName` attribute reported when running in k8s. Naming was taken from [HAproxy integration fix](https://github.com/newrelic/nri-haproxy/blob/master/src/collection.go#L160) . User that have been use `clusterName` attribute will need to replace it with `rabbitmqClusterName`.

Adds the `host:port` to all entity keys in order to use the entityRewrite when running in k8s. This fixes #73 . When the new version of the integration is deployed entities will be recreated with this new name. Old entities will live for an [extra day](https://github.com/newrelic/entity-definitions/blob/main/definitions/infra-rabbitmqqueue/definition.yml#L6).
example: 

`entityKey`(before):`ra-queue:/aliveness-test:clustername=rabbit@rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cluster.local`

`entityKey`(fixed):`ra-queue:k8s:k8s-cluster-name:rabbitmq:pod:rabbitmq-0:rabbitmq:15672:/aliveness-test:clustername=rabbit@rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cluster.local`

### CODE REVIEW

File: src/data/integration.go [hunk 1]
```diff
@@ -26,9 +26,7 @@ func CreateEntity(rabbitmqIntegration *integration.Integration, entityName, enti
 		name = joinVhostName(vhost, name)
 	}
 	metricNamespace = []attribute.Attribute{
-		{Key: "displayName", Value: name},
-		{Key: "entityName", Value: fmt.Sprintf("%s:%s", entityType, name)},
```
Comment (paologallinaharbur) [inline src/data/integration.go:30]: why also getting rid of those? Not needed anymore?

**Comment by paologallinaharbur** [comment]
I see it a painful change but needed, if we want to support this in the "long run" we should definitely go for it

File: src/data/integration.go (hunk 1 above)
Comment (gsanchezgavier) [reply src/data/integration.go:30]: Since once of the issues is that `name` collisions between clusters deployed in k8s, i think it will make names less confusing if we leave [the Agent to decorate this values ](https://github.com/newrelic/infrastructure-agent/blob/master/pkg/integrations/legacy/runner.go#L745). But is this might add another breaking change which it might be not required to do.

Comment (paologallinaharbur) [reply src/data/integration.go:30]: yeah, no idea if the best is to break "all at once" or avoid a further breaking change keeping a confusing metric there 😕

Comment (roobre) [reply src/data/integration.go:30]: As we talked, I'd suggest to not touch these for the time being. I do think it's better for the agent to generate this, but I don't see it's critical enough to risk breaking more things on this particular codebase.

**Review by roobre — APPROVED** [review]

**Comment by gsanchezgavier** [comment]
Blocked until end of April ( EOL time )
